# .github/workflows/frontend.yml

name: Frontend CI

on:
  push:
    branches: [ "landing-page" ]
  pull_request:
    branches: [ "landing-page" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Start project
        run: npm start
